# Generated by Django 5.1.2 on 2024-10-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Autoral'), (3, 'Escola'), (4, 'Ritinha'), (5, 'Amigos'), (6, 'Família')], default=1),
        ),
    ]
