# Generated by Django 5.1.2 on 2024-10-15 14:02

import reposit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposit', '0002_gallery_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=reposit.models.generate_image_filename),
        ),
    ]
