# Generated by Django 5.1.2 on 2024-10-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Autoral'), (3, 'Escola'), (4, 'Ritinha'), (5, 'Amigos'), (6, 'Família')], default=1),
        ),
    ]
